import { entry, type LatexDocumentation } from "@/features/editor/latex-docs/entry"

const command = (name: string, markdown: string): LatexDocumentation =>
  entry(`\\${name}`, markdown)

export const commandsMath = {
  acute: command("acute", "Places a short acute accent over a math atom. Use `\\hat` or `\\widehat` for hats over longer expressions."),
  allowdisplaybreaks: command("allowdisplaybreaks", "Allows page breaks within multi-line displayed mathematics. It is provided by `amsmath`; place it in the preamble when long derivations need it."),
  approx: command("approx", "Produces the approximately-equal relation `≈` in math mode."),
  arccos: command("arccos", "Typesets the inverse cosine operator with correct upright spacing."),
  arcsin: command("arcsin", "Typesets the inverse sine operator with correct upright spacing."),
  arctan: command("arctan", "Typesets the inverse tangent operator with correct upright spacing."),
  arg: command("arg", "Typesets the argument operator with correct upright spacing."),
  bar: command("bar", "Places a short bar over a math atom. Use `\\overline` when the material is wider."),
  big: command("big", "Selects a larger delimiter size, as in `\\bigl(`. Use paired sizing commands deliberately so delimiters remain readable."),
  Big: command("Big", "Selects a larger delimiter size than `\\big`, as in `\\Bigl[`."),
  bigg: command("bigg", "Selects a larger delimiter size than `\\Big`, as in `\\biggl\\{`."),
  Bigg: command("Bigg", "Selects the largest standard manual delimiter size, as in `\\Biggr\\}`."),
  binom: command("binom", "Creates a binomial coefficient without surrounding parentheses. It is provided by `amsmath`.\n\n```latex\n\\binom{n}{k}\n```"),
  bm: command("bm", "Makes a math symbol bold, including many symbols that `\\mathbf` cannot bold. It requires the `bm` package.\n\n```latex\n\\bm{\\alpha}\n```"),
  bmod: command("bmod", "Adds a binary `mod` operator with suitable spacing in a congruence."),
  boldsymbol: command("boldsymbol", "Makes a math symbol bold. It is provided by `amsmath`; prefer `\\bm` from the `bm` package when it supports the symbols you need."),
  breve: command("breve", "Places a breve accent over a math atom."),
  cdot: command("cdot", "Produces a centred multiplication dot in math mode."),
  coloneqq: command("coloneqq", "Produces a definition-equals relation with a leading colon. It is provided by `mathtools`, which extends `amsmath`."),
  cfrac: command("cfrac", "Creates a continued fraction with display-style numerators and denominators. It is provided by `amsmath`."),
  check: command("check", "Places a check accent over a math atom."),
  cos: command("cos", "Typesets the cosine operator with correct upright spacing."),
  cot: command("cot", "Typesets the cotangent operator with correct upright spacing."),
  csc: command("csc", "Typesets the cosecant operator with correct upright spacing."),
  dbinom: command("dbinom", "Creates a display-style binomial coefficient. It is provided by `amsmath`."),
  ddot: command("ddot", "Places two dots over a math atom, commonly for a second derivative."),
  DeclareMathOperator: command("DeclareMathOperator", "Declares a named math operator with correct upright type and spacing. It is provided by `amsmath` and belongs in the preamble.\n\n```latex\n\\DeclareMathOperator{\\rank}{rank}\n```"),
  deg: command("deg", "Typesets the degree operator with correct upright spacing."),
  det: command("det", "Typesets the determinant operator with correct upright spacing."),
  dfrac: command("dfrac", "Creates a display-style fraction even in inline math. It is provided by `amsmath`; reserve it for expressions that remain readable inline."),
  dim: command("dim", "Typesets the dimension operator with correct upright spacing."),
  displaystyle: command("displaystyle", "Forces display-math sizing for the following material. Use it sparingly inside inline math because it changes line height."),
  div: command("div", "Produces the division sign `÷` in math mode."),
  dot: command("dot", "Places one dot over a math atom, commonly for a time derivative."),
  equiv: command("equiv", "Produces the equivalence relation `≡` in math mode."),
  exists: command("exists", "Produces the existential quantifier `∃` in math mode."),
  exp: command("exp", "Typesets the exponential operator with correct upright spacing."),
  forall: command("forall", "Produces the universal quantifier `∀` in math mode."),
  frac: command("frac", "Creates a fraction with the required arguments `\\frac{numerator}{denominator}` in math mode.\n\n```latex\n$\\frac{a+b}{c}$\n```\n\nBrace multi-token numerators and denominators so their grouping is unambiguous. Use `\\dfrac` or `\\tfrac` from `amsmath` only when an explicit style is needed."),
  gcd: command("gcd", "Typesets the greatest-common-divisor operator with correct upright spacing."),
  geq: command("geq", "Produces the greater-than-or-equal relation `≥` in math mode."),
  grave: command("grave", "Places a grave accent over a math atom."),
  hat: command("hat", "Places a hat over a short math atom. Use `\\widehat` for a wider expression."),
  hom: command("hom", "Typesets the homomorphism operator with correct upright spacing."),
  iiint: command("iiint", "Creates a triple integral sign. It is provided by `amsmath`."),
  iint: command("iint", "Creates a double integral sign. It is provided by `amsmath`."),
  in: command("in", "Produces the set-membership relation `∈` in math mode."),
  inf: command("inf", "Typesets the infimum operator with limits in display math."),
  infty: command("infty", "Produces the infinity symbol `∞` in math mode."),
  int: command("int", "Produces an integral sign, with limits placed according to the current math style.\n\n```latex\n\\int_a^b f(x)\\,dx\n```"),
  intertext: command("intertext", "Inserts a short explanatory text line between rows of a multi-line display. It is provided by `amsmath` and is used inside environments such as `align`."),
  ker: command("ker", "Typesets the kernel operator with correct upright spacing."),
  left: command("left", "Automatically sizes the following delimiter to the enclosed material; pair it with `\\right`. Use `.` for an invisible counterpart.\n\n```latex\n\\left( \\frac{a}{b} \\right)\n```"),
  Leftarrow: command("Leftarrow", "Produces a double left arrow `⇐` in math mode."),
  leftarrow: command("leftarrow", "Produces a left arrow `←` in math mode."),
  leftrightarrow: command("leftrightarrow", "Produces a two-way arrow `↔` in math mode."),
  leq: command("leq", "Produces the less-than-or-equal relation `≤` in math mode."),
  lim: command("lim", "Typesets the limit operator with limits below and above in display math.\n\n```latex\n\\lim_{x \\to 0} \\frac{\\sin x}{x}\n```"),
  liminf: command("liminf", "Typesets the limit inferior operator. It is provided by `amsmath`."),
  limsup: command("limsup", "Typesets the limit superior operator. It is provided by `amsmath`."),
  ln: command("ln", "Typesets the natural-logarithm operator with correct upright spacing."),
  log: command("log", "Typesets the logarithm operator with correct upright spacing."),
  mapsto: command("mapsto", "Produces a mapping arrow `↦` in math mode."),
  mathbb: command("mathbb", "Typesets blackboard-bold mathematical letters. It requires `amsfonts` or `amssymb`.\n\n```latex\n$\\mathbb{R}$\n```"),
  mathbf: command("mathbf", "Typesets Latin letters and digits in bold upright math type. Use `\\bm` from the `bm` package for bold Greek letters or symbols."),
  mathcal: command("mathcal", "Typesets uppercase letters in calligraphic math type.\n\n```latex\n$\\mathcal{F}$\n```"),
  mathfrak: command("mathfrak", "Typesets Fraktur mathematical letters. It requires `amsfonts` or `amssymb`."),
  mathit: command("mathit", "Typesets its argument in italic math type, useful for multi-letter variable names."),
  mathring: command("mathring", "Places a small ring accent over a math atom."),
  mathrm: command("mathrm", "Typesets its argument in upright roman math type, useful for units or named constants."),
  mathscr: command("mathscr", "Typesets script-style mathematical letters when a package such as `mathrsfs` provides it. Check the selected math font package’s documentation."),
  mathsf: command("mathsf", "Typesets its argument in sans-serif math type."),
  mathtt: command("mathtt", "Typesets its argument in monospaced math type."),
  max: command("max", "Typesets the maximum operator with limits in display math."),
  min: command("min", "Typesets the minimum operator with limits in display math."),
  mod: command("mod", "Formats a parenthesised modulus expression, as in `a \\equiv b \\mod n`."),
  mp: command("mp", "Produces the minus-or-plus symbol `∓` in math mode."),
  nabla: command("nabla", "Produces the nabla symbol `∇` in math mode."),
  neq: command("neq", "Produces the not-equal relation `≠` in math mode."),
  notin: command("notin", "Produces the not-an-element-of relation `∉` in math mode."),
  nonumber: command("nonumber", "Suppresses the number for the current row of an `amsmath` multi-line display."),
  notag: command("notag", "Suppresses the tag for the current row of an `amsmath` multi-line display; it is an alias for `\\nonumber`."),
  numberwithin: command("numberwithin", "Resets one counter within another and includes the parent number. It is provided by `amsmath`, for example `\\numberwithin{equation}{section}`."),
  oint: command("oint", "Produces a closed contour integral sign."),
  operatorname: command("operatorname", "Typesets a one-off named operator with correct upright spacing. It is provided by `amsmath`.\n\n```latex\n\\operatorname{rank}(A)\n```\n\nUse `\\DeclareMathOperator` for a reusable name."),
  overset: command("overset", "Places one math expression above another. It is provided by `amsmath`."),
  partial: command("partial", "Produces the partial-derivative symbol `∂` in math mode."),
  pm: command("pm", "Produces the plus-or-minus symbol `±` in math mode."),
  pmod: command("pmod", "Formats a parenthesised modulus expression with appropriate spacing."),
  pod: command("pod", "Formats a parenthesised modulus expression without adding the word `mod`."),
  Pr: command("Pr", "Typesets the probability operator with correct upright spacing."),
  prod: command("prod", "Produces a product operator with limits in display math.\n\n```latex\n\\prod_{i=1}^n i\n```"),
  qedhere: command("qedhere", "Places the proof-ending symbol at the current location. It is provided by `amsthm`, usually inside a proof environment."),
  raisetag: command("raisetag", "Adjusts a display equation tag vertically. It is provided by `amsmath`; use it only to correct a genuine collision."),
  right: command("right", "Completes a `\\left` delimiter pair and automatically matches its size. Use `.` when the closing delimiter should be invisible."),
  Rightarrow: command("Rightarrow", "Produces a double right arrow `⇒` in math mode."),
  rightarrow: command("rightarrow", "Produces a right arrow `→` in math mode. `\\to` is a common alias."),
  scriptscriptstyle: command("scriptscriptstyle", "Switches to the smallest standard math style, normally used automatically in nested scripts."),
  scriptstyle: command("scriptstyle", "Switches to script-sized math, normally used automatically in subscripts and superscripts."),
  sec: command("sec", "Typesets the secant operator with correct upright spacing."),
  shoveleft: command("shoveleft", "Moves a line left within an `amsmath` `multline` display. Use it only when the default alignment is unsuitable."),
  shoveright: command("shoveright", "Moves a line right within an `amsmath` `multline` display. Use it only when the default alignment is unsuitable."),
  sideset: command("sideset", "Adds left-side scripts to a large operator. It is provided by `amsmath`."),
  sim: command("sim", "Produces the similarity relation `∼` in math mode."),
  simeq: command("simeq", "Produces the similarity-or-approximately-equal relation `≃` in math mode."),
  sin: command("sin", "Typesets the sine operator with correct upright spacing."),
  sqrt: command("sqrt", "Creates a square root; an optional argument supplies a root index.\n\n```latex\n$\\sqrt[n]{x}$\n```"),
  stackrel: command("stackrel", "Places a short annotation above a relation. Prefer `\\overset` from `amsmath` for the more general form."),
  subset: command("subset", "Produces the subset relation `⊂` in math mode."),
  subseteq: command("subseteq", "Produces the subset-or-equal relation `⊆` in math mode."),
  substack: command("substack", "Stacks short lines in a subscript or superscript. It is provided by `amsmath`.\n\n```latex\n\\sum_{\\substack{i=1\\\\j=1}}^n a_{ij}\n```"),
  sum: command("sum", "Produces a summation operator with limits in display math.\n\n```latex\n\\sum_{i=1}^n i\n```"),
  sup: command("sup", "Typesets the supremum operator with limits in display math."),
  supset: command("supset", "Produces the superset relation `⊃` in math mode."),
  supseteq: command("supseteq", "Produces the superset-or-equal relation `⊇` in math mode."),
  tag: command("tag", "Sets a custom equation tag in a numbered `amsmath` display. Use it sparingly so cross-references remain clear.\n\n```latex\n\\tag{*}\n```"),
  tan: command("tan", "Typesets the tangent operator with correct upright spacing."),
  tbinom: command("tbinom", "Creates a text-style binomial coefficient. It is provided by `amsmath`."),
  text: command("text", "Inserts a short text-mode phrase inside mathematics while preserving surrounding spacing. It is provided by `amsmath`.\n\n```latex\n$x > 0 \\text{ for all } x$\n```"),
  textstyle: command("textstyle", "Forces text-math sizing for the following material, useful in compact displays when used deliberately."),
  tilde: command("tilde", "Places a tilde accent over a math atom. Use `\\widetilde` for a wider expression."),
  times: command("times", "Produces the multiplication sign `×` in math mode."),
  to: command("to", "Produces a right arrow `→` in math mode; it is an alias for `\\rightarrow`."),
  tfrac: command("tfrac", "Creates a text-style fraction even in display math. It is provided by `amsmath`."),
  underbrace: command("underbrace", "Draws a brace below an expression; attach an annotation with a subscript.\n\n```latex\n\\underbrace{a+b}_{\\text{sum}}\n```"),
  underset: command("underset", "Places one math expression below another. It is provided by `amsmath`."),
  vec: command("vec", "Places a vector arrow over a short math atom. Use a bold-vector convention consistently across the document."),
  widehat: command("widehat", "Places a wide hat over a multi-character expression."),
  widetilde: command("widetilde", "Places a wide tilde over a multi-character expression."),
  xleftarrow: command("xleftarrow", "Creates an extensible left arrow with an annotation. It is provided by `amsmath`.\n\n```latex\nA \\xleftarrow{f} B\n```"),
  xrightarrow: command("xrightarrow", "Creates an extensible right arrow with an annotation. It is provided by `amsmath`.\n\n```latex\nA \\xrightarrow{f} B\n```"),
} as const satisfies Readonly<Record<string, LatexDocumentation>>
