import { entry, type LatexDocumentation } from "@/features/editor/latex-docs/entry"

const command = (name: string, markdown: string): LatexDocumentation =>
  entry(`\\${name}`, markdown)

export const commandsText = {
  addtolength: command("addtolength", "Adds a dimension to an existing length.\n\n```latex\n\\addtolength{\\textwidth}{1cm}\n```\n\nUse sparingly because layout lengths interact with the document class."),
  bfseries: command("bfseries", "Switches to the current family’s bold series until the enclosing group ends. Prefer `\\textbf{...}` for a short span."),
  bigskip: command("bigskip", "Inserts a large flexible vertical space. Use document structure or a named length instead when spacing conveys meaning."),
  cdots: command("cdots", "Produces centred horizontal dots for multiplication or other binary relations in math mode."),
  centering: command("centering", "Centres following material within the current group or environment.\n\n```latex\n\\begin{figure}\n  \\centering\n  \\includegraphics{plot}\n\\end{figure}\n```\n\nUnlike `center`, it does not add vertical space."),
  color: command("color", "Changes the current text colour until the enclosing group ends. It requires the `xcolor` or `color` package.\n\n```latex\n{\\color{red} Important text}\n```"),
  colorbox: command("colorbox", "Draws a coloured background behind text. It requires the `xcolor` or `color` package.\n\n```latex\n\\colorbox{yellow}{Draft}\n```"),
  copyright: command("copyright", "Produces the copyright symbol in text mode."),
  dag: command("dag", "Produces a dagger symbol, commonly used as a footnote marker."),
  ddag: command("ddag", "Produces a double-dagger symbol, commonly used as a footnote marker."),
  ddots: command("ddots", "Produces descending diagonal dots in math mode, often inside a matrix."),
  definecolor: command("definecolor", "Defines a named colour from a colour model and components. It requires the `xcolor` or `color` package.\n\n```latex\n\\definecolor{accent}{RGB}{0, 94, 184}\n```"),
  emph: command("emph", "Emphasises text, usually with italics, while adapting correctly inside already italic text.\n\n```latex\n\\emph{Important distinction}\n```"),
  enspace: command("enspace", "Inserts a horizontal space approximately the width of an en dash."),
  fbox: command("fbox", "Draws a framed box around its contents.\n\n```latex\n\\fbox{Key result}\n```\n\nUse `\\fcolorbox` for a coloured frame or background."),
  fcolorbox: command("fcolorbox", "Draws a coloured frame and background around text. It requires the `xcolor` or `color` package.\n\n```latex\n\\fcolorbox{blue}{white}{Note}\n```"),
  fontsize: command("fontsize", "Selects a font size and baseline skip; follow it with `\\selectfont`. Prefer named sizes for normal document text.\n\n```latex\n\\fontsize{11}{13}\\selectfont\n```"),
  footnote: command("footnote", "Adds a numbered footnote at the current location.\n\n```latex\nA claim\\footnote{Source details.}\n```\n\nAvoid footnotes in headings and moving arguments unless the class supports them."),
  footnotesize: command("footnotesize", "Switches to the class-defined footnote font size until the enclosing group ends."),
  framebox: command("framebox", "Draws a framed box with optional width and alignment. Use `\\fbox` when the natural-width box is sufficient."),
  hfill: command("hfill", "Inserts stretchable horizontal space that expands to fill the current line."),
  hspace: command("hspace", "Inserts horizontal space of a chosen length.\n\n```latex\nName\\hspace{1em}Value\n```\n\nUse `\\hspace*` to preserve the space at a line break."),
  huge: command("huge", "Switches to a large class-defined font size until the enclosing group ends."),
  Huge: command("Huge", "Switches to the largest standard class-defined font size until the enclosing group ends."),
  indent: command("indent", "Forces indentation at the start of a paragraph when LaTeX would otherwise suppress it."),
  item: command("item", "Adds an entry to a list-like environment such as `itemize`, `enumerate`, or `description`.\n\n```latex\n\\begin{enumerate}\n  \\item First step\n\\end{enumerate}\n```\n\nUsing it outside a compatible environment causes an error."),
  itshape: command("itshape", "Switches to the current family’s italic shape until the enclosing group ends. Prefer `\\textit{...}` for a short span."),
  large: command("large", "Switches to a class-defined font size larger than `\\normalsize` until the enclosing group ends."),
  Large: command("Large", "Switches to a class-defined font size larger than `\\large` until the enclosing group ends."),
  LARGE: command("LARGE", "Switches to a class-defined font size larger than `\\Large` until the enclosing group ends."),
  LaTeX: command("LaTeX", "Produces the LaTeX logo with its conventional spacing."),
  LaTeXe: command("LaTeXe", "Produces the LaTeX2e logo with its conventional spacing."),
  ldots: command("ldots", "Produces baseline horizontal dots, useful in prose or a sequence."),
  makebox: command("makebox", "Creates a horizontal box with optional width and alignment. Use it to reserve measured space without drawing a frame."),
  marginpar: command("marginpar", "Places a note in the current margin. Its side and placement depend on the page layout and class."),
  mbox: command("mbox", "Makes its contents an unbreakable horizontal box.\n\n```latex\nFigure~\\mbox{\\ref{fig:overview}}\n```\n\nUse it only for short material; long boxes can overrun the margin."),
  mdseries: command("mdseries", "Switches to the current family’s medium weight until the enclosing group ends."),
  medskip: command("medskip", "Inserts a medium flexible vertical space."),
  noindent: command("noindent", "Suppresses indentation for the current paragraph only."),
  normalsize: command("normalsize", "Restores the document class’s normal font size and baseline skip."),
  P: command("P", "Produces the paragraph symbol in text mode."),
  pagecolor: command("pagecolor", "Sets the page background colour. It requires the `xcolor` or `color` package. Use it deliberately because it affects the whole page."),
  parbox: command("parbox", "Creates a fixed-width box containing one or more paragraphs.\n\n```latex\n\\parbox{0.4\\textwidth}{Wrapped explanatory text.}\n```"),
  pounds: command("pounds", "Produces the pound sterling symbol in text mode."),
  quad: command("quad", "Inserts horizontal space equal to one em."),
  qquad: command("qquad", "Inserts horizontal space equal to two ems."),
  raggedleft: command("raggedleft", "Sets following paragraphs flush right with a ragged left edge until the enclosing group ends."),
  raggedright: command("raggedright", "Sets following paragraphs flush left with a ragged right edge until the enclosing group ends."),
  raisebox: command("raisebox", "Raises or lowers a box by a specified length.\n\n```latex\n\\raisebox{0.5ex}{*}\n```\n\nUse optional height and depth only when the box’s layout dimensions must change."),
  rmfamily: command("rmfamily", "Switches to the document’s roman font family until the enclosing group ends."),
  rowcolors: command("rowcolors", "Applies alternating row colours to tabular rows. It requires the `xcolor` package with the `table` option.\n\n```latex\n\\usepackage[table]{xcolor}\n\\rowcolors{2}{gray!15}{white}\n```"),
  rule: command("rule", "Draws a solid rectangle with a width and height.\n\n```latex\n\\rule{1cm}{0.4pt}\n```\n\nAn optional raise amount moves it vertically."),
  S: command("S", "Produces the section symbol in text mode."),
  scshape: command("scshape", "Switches to the current family’s small-caps shape until the enclosing group ends."),
  scriptsize: command("scriptsize", "Switches to a small class-defined font size, commonly suitable for annotations, until the enclosing group ends."),
  selectfont: command("selectfont", "Activates a font selection made with low-level font commands such as `\\fontsize`. Most named font switches activate automatically."),
  setlength: command("setlength", "Sets the value of a length parameter, which controls spacing and sizing in LaTeX.\n\n```latex\n\\setlength{\\parindent}{0pt}\n```\n\nSome lengths are class-specific."),
  setmainfont: command("setmainfont", "Selects the main text font when compiling with XeLaTeX or LuaLaTeX. It is supplied by the `fontspec` package.\n\n```latex\n\\usepackage{fontspec}\n\\setmainfont{Times New Roman}\n```\n\nDo not use it with pdfLaTeX; choose an engine before setting fonts."),
  settodepth: command("settodepth", "Sets a length to the depth of typeset material. Use it for layout that must account for descenders."),
  settoheight: command("settoheight", "Sets a length to the height of typeset material."),
  settowidth: command("settowidth", "Sets a length to the width of typeset material.\n\n```latex\n\\settowidth{\\labelwidth}{Longest label}\n```"),
  sffamily: command("sffamily", "Switches to the document’s sans-serif font family until the enclosing group ends."),
  small: command("small", "Switches to a class-defined font size smaller than `\\normalsize` until the enclosing group ends."),
  smallskip: command("smallskip", "Inserts a small flexible vertical space."),
  stretch: command("stretch", "Produces a rubber length that expands by the given factor. It is useful in glue expressions such as `\\vspace{\\stretch{1}}`."),
  TeX: command("TeX", "Produces the TeX logo with its conventional spacing."),
  textbf: command("textbf", "Typesets a short text span in bold.\n\n```latex\n\\textbf{Warning:} check the units.\n```"),
  textcolor: command("textcolor", "Typesets its text argument in a named colour. It requires the `xcolor` or `color` package.\n\n```latex\n\\textcolor{red}{Review this value.}\n```"),
  textmd: command("textmd", "Typesets a short text span in the medium series."),
  textnormal: command("textnormal", "Typesets a short text span using the surrounding document’s normal font settings."),
  textrm: command("textrm", "Typesets a short text span in the roman font family."),
  textsc: command("textsc", "Typesets a short text span in small caps when the current font provides them."),
  textsf: command("textsf", "Typesets a short text span in the sans-serif font family."),
  textsl: command("textsl", "Typesets a short text span in a slanted shape when the current font provides one."),
  textsubscript: command("textsubscript", "Typesets a text-mode subscript. Use math subscripts for mathematical notation."),
  textsuperscript: command("textsuperscript", "Typesets a text-mode superscript.\n\n```latex\n4\\textsuperscript{th} edition\n```"),
  texttt: command("texttt", "Typesets a short text span in the monospaced font family."),
  textup: command("textup", "Typesets a short text span in an upright shape."),
  tiny: command("tiny", "Switches to the smallest standard class-defined font size until the enclosing group ends."),
  today: command("today", "Expands to today’s date using the current language’s date format. It is often used in `\\date{\\today}`."),
  ttfamily: command("ttfamily", "Switches to the document’s monospaced font family until the enclosing group ends."),
  underline: command("underline", "Underlines text. It cannot normally break across lines, so use it only for short spans."),
  upshape: command("upshape", "Switches to an upright font shape until the enclosing group ends."),
  vdots: command("vdots", "Produces vertical dots in math mode, often inside a matrix."),
  verb: command("verb", "Typesets literal characters in a monospaced style.\n\n```latex\n\\verb|path_with_underscores|\n```\n\nIt cannot be used in moving arguments such as section titles."),
  vfill: command("vfill", "Inserts stretchable vertical space that expands to fill the current page or vertical box."),
  vspace: command("vspace", "Inserts vertical space of a chosen length.\n\n```latex\n\\vspace{1em}\n```\n\nUse `\\vspace*` to preserve the space at the top or bottom of a page."),
} as const satisfies Readonly<Record<string, LatexDocumentation>>
